# try-catch-finally 구문
* 자원 사용 후, 어느 상황이던지(에러상황포함) 자원희 닫힘을 보장하기 위해 주로 사용
```java
String getFirstLineOfFile(String path) throws IOException {
	BufferedReader bufferedReader = new BufferedReader(new FileReader(path));
    
	try {
		return bufferedReader.readLine();
	} catch (IOException e) {
		e.printStackTrace();
	} finally {
		bufferedReader.close();
	}
}
```

# try-finally 구문을 이용한 자원 해제의 문제점
1. 닫아줘야 하는 자원이 2개 이상이 되면 중첩 try-catch-finally 문으로 인해 코드가 매우 지저분해진다.
```java
public boolean reandAndWriteFile(String sourcePath, String targetPath) throws IOException{
	String line;
	BufferedReader bufferedReader = new BufferedReader(new FileReader(sourcePath));
	try {
		BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(targetPath));
		try {
			while (true) {
				if ((line = bufferedReader.readLine()) != null)){
					bufferedWriter.write(line);
				}
			}
		} finally {
			bufferedWriter.close();
			return false;
		}
	} finally {
		bufferedReader.close();
		return false;
	}
	return true;
}
```

2. (기기등의 문제로) 파일 읽기/쓰기 뿐만 아니라 자원 닫기에서도 에러 발생시 콜스택에 자원 닫기 실패에 대한 정보만 기록되고 try 블록에서 발생한 첫번째 예외(파일 읽기/쓰기 실패) 정보가 사라짐
```java
public class FirstError extends RuntimeException{}

public class SecondError extends RuntimeException{}

public class CallStackEx implements AutoCloseable {
	public void doSomething() {
		throw new FirstError();
	}

	@Override
	public void close() {
		throw new SecondError();
	}

	public static void main(String[] args) {
		CallStackEx myResource = new CallStackEx();
		try {
			myResource.doSomething();
		} finally {
			myResource.close();        
		}
	}
}
```
```java
//콜스택 - FirstError에 대한 정보가 사라짐
Exception in thread "main" CallStackEx.SecondError		
	at CallStackEx.CallStackEx.close(CallStackEx.java:10)
	at CallStackEx.CallStackEx.main(CallStackEx.java:18)

Process finished with exit code 1

```
3. 위와같은 문제를 해결하기 위해 close() 메서드를 try-catch 로 감싸기도 하는데 이는 가독성을 더욱 떨어뜨린다.
```java
public static void main(String[] args) {
	CallStackEx myResource = new CallStackEx();
	try {
		myResource.doSomething();
	} finally {
		try {
			myResource.close();
		} catch (Exception e) {
			logger.severe(e.getMessage());
		}
	}
}
```
```java
//콜스택 - FirstError 를 보여주긴 한다.
1월 10, 2020 10:36:47 오후 CallStackEx.CallStackEx testMethod_2
심각: null
Exception in thread "main" CallStackEx.FirstError
	at CallStackEx.CallStackEx.doSomething(CallStackEx.java:9)
	at CallStackEx.CallStackEx.testMethod_2(CallStackEx.java:29)
	at CallStackEx.CallStackEx.main(CallStackEx.java:40)

Process finished with exit code 1
``` 


# try-with-resource
* java 1.7 에서부터 추가된 기능으로 기존 try-finally 구문의 자원해제 단점보완
* 해제하고자 하는 자원이 AutoCloseable 인터페이스를 구현하고 있어야함(대부분의 써드파티라이브러리들에 구현되어있음)
### 장점
1. try-finally 에 비해 코드가 간결하고 가독성이 좋다
```java
	public static void main(String[] args) {
		
	//try-finally 구문
	MyResource myResource = new MyResource();
	try {
		myResource.doSomething();
	} finally {
		try {
			myResource.close();
		} catch (Exception e) {
			logger.severe(e.getMessage());
		}
	}
	
	//try-with-resource 구문
   	try (MyResource myResource = new MyResource()) {
		myResource.doSomething();
   	}
	
   	//========================================================
   	//try-finally 구문
	MyResource myResource = new MyResource();
	try {
		myResource.doSomething();
		MyResource myResource2 = null;
		try {
			myResource2 = new MyResource();
			myResource2.doSomething();
			finally {
				if(myResource2 != null) {
					try {
						myResource2.close();
					} catch (Exception e) {
						logger.severe(e.getMessage());
					}
				}
			}
		}
	} finally {
		try {
			myResource.close();
		} catch (Exception e) {
			logger.severe(e.getMessage());
		}
	}
	
	//try-with-resource 구문
	try (MyResource myResource = new MyResource(); MyResource myResource2 = new MyResource()) {
		myResource.doSomething();
		myResource2.doSomething();
	}
}
```
2. 자원해제시 예외가 발생해도 try 블록에서 발생한 예외가 누락되지 않고 모두 콜스택에 남는다.
> 자원 해제과정에서 발생한 예외도 콜스택에 Suppressed 태그(숨겨졌다는 의미)를 달고 출력됨
```java
public static void main(String[] args) {
	try (MyResource myResource = new MyResource()) {
		myResource.doSomething();
	}
}
```
```java
//콜스택
Exception in thread "main" FirstError
	at MyResource.doSomething(MyResource.java:4)
	at Main.main(Main.java:5)
	Suppressed: SecondError
		at MyResource.close(MyResource.java:10)
	at Main.main(Main.java:6)

Process finished with exit code 1
```


### 실제로 얼마나 줄어들까?
```java
//압축다운로드 기존 소스
try {
	inputStream = getInputStream(model);
	if (downloadTranslator == null) {
		...
	} else {
		try {
			isr = new InputStreamReader(inputStream, encoding);
			br = new BufferedReader(isr);
		} finally {
			if (br != null) {
				try {
					br.close();
				} catch (IOException ex) {
					logger.error(ex.toString(), ex);
				}
			}
			if (isr != null) {
				try {
					isr.close();
				} catch (IOException ex) {
					logger.error(ex.toString(), ex);
				}
			}
		}
	}
} finally {
	if (inputStream != null) {
		try {
			inputStream.close();
		} catch (IOException ex) {
			logger.error(ex.toString(), ex);
		}
	}
}


//수정 후 소스
try (InputStream inputStream = getInputStream(model)) {
	if (downloadTranslator == null) {
		...
	} else {
		try (InputStreamReader isr = new InputStreamReader(inputStream, ZipConstants.CHARSET_UTF8); BufferedReader br = new BufferedReader(isr)) {
		}
	}
}
```
```java
//tomcat log
2020-01-22 14:44:30 [DEBUG](DispatcherServlet.java:1286) Error rendering view [com.naver.ndrive.compress.common.web.view.FileDownloadView: name 'fileDownloadView'] in DispatcherServlet with name 'appServlet'
com.naver.ndrive.compress.common.exception.ServiceException: 500:INTERNAL_SERVER_ERROR:500:Exception in readLine
	at com.naver.ndrive.compress.service.view.model.BufferedReaderImpl.readLine(BufferedReaderImpl.java:17) ~[classes/:?]
	at com.naver.ndrive.compress.common.web.view.FileDownloadView.downloadFile(FileDownloadView.java:81) ~[classes/:?]
	...
	Suppressed: com.naver.ndrive.compress.common.exception.ServiceException: 500:INTERNAL_SERVER_ERROR:500:Exception in close
		at com.naver.ndrive.compress.service.view.model.BufferedReaderImpl.close(BufferedReaderImpl.java:22) ~[classes/:?]
		at com.naver.ndrive.compress.common.web.view.FileDownloadView.downloadFile(FileDownloadView.java:82) ~[classes/:?]
		...
```